[build]
  publish = "."
  # the root website directory
  command = "echo 'I be building' "
  # the build command
  functions = "func/"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/excuse"
  status = 200
