[build]
  publish = "."
  command = "npm run build"
  functions = "functions/"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/excuse"
  status = 200

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"